title: Bugzilla
email: developers@bugzilla.org
description: >
  The software solution designed to drive software development, which
  lets you plan, organize and release software on your own teams'
  schedule.
baseurl: ""
url: "https://www.bugzilla.org"
source_code: https://github.com/bugzilla/bugzilla
list_bugs: https://bugzilla.mozilla.org/buglist.cgi?product=Bugzilla
report_bug: https://bugzilla.mozilla.org/enter_bug.cgi?product=Bugzilla
theme: jekyll-theme-bugzilla@main
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Bugzilla Team
      breadcrumbs:
      - name: Blog
        link: /blog/
      permalink: /blog/:year/:month/:day/:title/
      ogtype: article
  -
    scope:
      path: ""
      type: "security"
    values:
      layout: security
      breadcrumbs:
      - name: Security Advisories
        link: /security/
      ogtype: article
  -
    scope:
      path: ""
      type: "releases"
    values:
      layout: release
      mode: ""
      rc: false
      breadcrumbs:
      - name: Releases
        link: /releases/
      ogtype: article
  -
    scope:
      path: ""
      type: "developers"
    values:
      layout: profile
      breadcrumbs:
      - name: Developers
        link: /about/developers/
      ogtype: profile
  -
    scope:
      path: "/contributing/*"
    values:
      breadcrumbs:
      - name: Contributing
        link: /contributing/
  -
    scope:
      path: "/support/*"
    values:
      breadcrumbs:
      - name: Support
        link: /support/
  -
    scope:
      path: "/about/*"
    values:
      breadcrumbs:
      - name: About
        link: /about/

paginate: 10
paginate_path: "/blog/page/:num/"

collections:
  developers:
    output: true
    permalink: /about/:collection/:path/
  security:
    output: true
    permalink: /:collection/:path/
  releases:
    output: true
    permalink: /:collection/:path/
